---
- name: build hosts file
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}" state=present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ play_hosts }}"

- name: install PyYAML
  yum:
    name: PyYAML
    state: latest

- name: enable selinux
  selinux:
    policy: targeted
    state: enforcing

- name: Reboot server
  shell: "sleep 3; /usr/sbin/shutdown -r now"
  async: 1
  poll: 0
  failed_when: false
  changed_when: true
  ignore_errors: true
  when: ansible_ssh_host != '127.0.0.1'

- name: Wait for reboot to start
  pause:
    seconds: 5

- name: waiting for system to come online
  wait_for: host="{{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }}" port="{{ hostvars[inventory_hostname].ansible_ssh_port | default('22') }}" search_regex=OpenSSH
  delegate_to: 127.0.0.1
  become: no
  when: inventory_hostname != '127.0.0.1' or hostvars[inventory_hostname].ansible_host != '127.0.0.1'



