- hosts: all:!new_nodes:!parking
  gather_facts: no
  pre_tasks:
    - name: gather facts
      setup:
      when:
        - groups.windows is defined
        - inventory_hostname in groups.windows
  roles:
    - hosts-file