- hosts: masters
  become: yes
  tasks:

    - name: create a system account
      shell: oc create sa pv-recycler-controller -n openshift-infra
      run_once: yes

    - name: add priviliged
      shell: oc adm policy add-scc-to-user privileged -z pv-recycler-controller -n openshift-infra
      run_once: yes

    - name: add role to system account
      shell: oc adm policy add-cluster-role-to-user system:openshift:controller:pv-recycler-controller pv-recycler-controller -n openshift-infra
      run_once: yes

    - name: allow non-root images
      shell: oc adm policy add-scc-to-group anyuid system:authenticated
      run_once: yes