- hosts: masters[0]
  become: yes
  become_user: root
  roles:
    - openshift-win-ovn-build


- hosts: windows
  become_user: Administrator
  become_method: runas
  gather_facts: no
  roles:
    - openshift-win-prereqs

- hosts: windows
  gather_facts: no
  serial: 1
  tasks:
    - include_role:
        name: openshift-win-node-config
        apply:
          delegate_to: "{{ groups.masters | first }}"

- hosts: masters[0]
  become: yes
  become_user: root
  vars:
    user: "{{lookup('env','USER')}}"
  roles:
    - openshift-win-gather-config

- hosts: windows
  become: no
  gather_facts: no
  serial: 1
  roles:
    - openshift-win-node-deploy

- hosts: masters[0]
  gather_facts: no
  become: yes
  roles:
    - openshift-win-cni-config

- hosts: windows
  become: no
  serial: 1
  roles:
    - openshift-win-ovn-deploy