- hosts: masters
  become: yes
  tasks:
  #check existing sa for openshift-infra
  #oc get sa -n openshift-infra
  #try this next -> oc adm policy add-scc-to-user hostmount-anyuid system:serviceaccount:openshift-infra:pv-recycler-controller
  #to allow non-root low id
  #oadm policy add-scc-to-user nonroot -z default
  #oc adm policy add-scc-to-group anyuid system:authenticated
    - name: create a system account
      shell: oc create sa pv-recycler-controller -n openshift-infra
      ignore_errors: yes
      run_once: yes

    - name: add priviliged
      shell: oc adm policy add-scc-to-user privileged -z pv-recycler-controller -n openshift-infra
      run_once: yes

    - name: add role to system account
      shell: oc adm policy add-cluster-role-to-user system:openshift:controller:pv-recycler-controller pv-recycler-controller -n openshift-infra
      run_once: yes

    - name: allow non-root images
      shell: oc adm policy add-scc-to-group anyuid system:authenticated
      run_once: yes

    - name: read origin master configuration data
      shell: cat /etc/origin/master/master-config.yaml | grep -q 'HTPasswdPasswordIdentityProvider'
      register: master_config
      ignore_errors: yes

    - name: add user
      command: htpasswd -c -b /etc/origin/master/htpasswd {{ lookup('env','K8S_AUTH_USERNAME') }} {{ lookup('env','K8S_AUTH_PASSWORD') }}
      when: master_config is success

- hosts: nodes
  become: yes
  tasks:
    # this is needed to prevent upstream dns to answer for default.svc
    # resolution needs to be local
    - name: add default.svc.cluster.local to dnsmasq configuration file
      lineinfile:
        path: '{{ item }}'
        insertbefore: '^server=/cluster.local*'
        line: 'server=/default.svc.cluster.local/127.0.0.1'
      with_items:
        - /etc/dnsmasq.d/node-dnsmasq.conf
        - /etc/origin/node/node-dnsmasq.conf
      ignore_errors: yes

    # This is needed for Prometheus to pull node exporter metrics at http://localhost:9100/metrics from all nodes
    # This is not done as of OpenShift 3.9
    - name: open destination port tcp/9100
      iptables:
        chain: OS_FIREWALL_ALLOW
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT
        destination_port: 9100
        protocol: tcp
        match: conntrack
      when:
        - os_firewall_use_firewalld is not defined
        - not os_firewall_use_firewalld

    - name: open source port tcp/9100
      iptables:
        chain: OS_FIREWALL_ALLOW
        ctstate: NEW,ESTABLISHED
        jump: ACCEPT
        source_port: 9100
        protocol: tcp
        match: conntrack
      when:
        - os_firewall_use_firewalld is not defined
        - not os_firewall_use_firewalld

    - name: save iptables rules
      command: service iptables save
      when:
        - os_firewall_use_firewalld is not defined
        - not os_firewall_use_firewalld