- hosts: all:!new_nodes:!parking
  become: yes
  gather_facts: no
  pre_tasks:
    - name: gather facts
      setup:
      when: groups.windows is not defined or inventory_hostname not in groups.windows
  roles:
    - hosts-file
    - oatakan.rhn
    - openshift-prepare