- hosts: masters
  become: yes
  tasks:
    - name: create a new project
      shell: oc adm new-project openshift-metrics-node-exporter --node-selector='zone=default'
      run_once: yes

    - name: create node-exporter daemonset
      shell: oc create -f https://raw.githubusercontent.com/openshift/origin/master/examples/prometheus/node-exporter.yaml -n openshift-metrics-node-exporter
      run_once: yes

    - name: add policy
      shell: oc adm policy add-scc-to-user -z prometheus-node-exporter -n openshift-metrics-node-exporter hostaccess
      run_once: yes

