- hosts: all:!new_nodes:!parking
  become: yes
  gather_facts: no
  pre_tasks:
    - name: gather facts
      setup:
      when: ansible_os_family == 'RedHat'
  roles:
    - hosts-file
    - oatakan.rhn
    - openshift-prepare