- hosts: masters[0]
  become: yes
  tasks:
    - name: wait for oc client to be available
      wait_for:
        path: /usr/bin/oc
        timeout: 36000

    - name: wait for kubeconfig to be available
      wait_for:
        path: /root/.kube/config
        timeout: 36000

    - name: wait for API response
      shell: oc whoami | grep -m 1 "system:admin"
      register: wait_for_api
      until: wait_for_api is success
      retries: 300
      delay: 5

#    - name: open firewall {{ item }}
#      shell: iptables -A IN_public_allow -p tcp -m state --state NEW -m tcp --dport {{ item }} -j ACCEPT
#      loop:
#        - 6641
#        - 6642
#        - 6081

#    - name: open ports for ovn
#      iptables:
#        chain: IN_public_allow
#        ctstate: NEW
#        jump: ACCEPT
#        destination_port: '{{ item }}'
#        protocol: tcp
#        match: state
#      loop:
#        - "6641"
#        - "6642"
#        - "6081"
#
#    - name: Save iptables rules
#      shell: service iptables save

    - name: open ports for ovn
      firewalld:
        zone: public
        port: '{{ item }}/tcp'
        permanent: yes
        state: enabled
      loop:
        - "6641"
        - "6642"
        - "6081"

    - name: Remove OVS DB Content
      shell: rm -rf /var/lib/openvswitch/ovn*.db

    - name: Remove any old ovn-kubernets
      shell: rm -r -f ~/ovn-kubernetes

    - name: Clone ovn-kubernetes
      shell: git clone https://github.com/glennswest/ovn-kubernetes  ~/ovn-kubernetes

    - name: Provision the OVN Namespace
      shell: oc create -f /root/ovn-kubernetes/dist/yaml/ovn-namespace.yaml
      ignore_errors: yes

    - name: Provision the OVN Policy
      shell: oc create -f /root/ovn-kubernetes/dist/yaml/ovn-policy.yaml
      ignore_errors: yes

    - name: Provision the OVN Project
      shell: oc project ovn-kubernetes
      ignore_errors: yes

    - name: Add adm policy auyuid
      shell: oc adm policy add-scc-to-user anyuid -z ovn
      ignore_errors: yes

    - name: Run the ovn-setup
      shell: cd ~/ovn-kubernetes/dist/ansible/scripts; ./ovn-setup.sh > ovn-setup.out
      ignore_errors: yes

    - name: Start the ovn-ovs daemonset
      shell: oc create -f /root/ovn-kubernetes/dist/yaml/sdn-ovs.yaml
      ignore_errors: yes

    - name: Start the master ovn daemonset
      shell: oc create -f /root/ovn-kubernetes/dist/yaml/ovnkube-master.yaml
      ignore_errors: yes

    - name: Create node daemonset
      shell: oc create -f /root/ovn-kubernetes/dist/yaml/ovnkube.yaml
      ignore_errors: yes

    - block:
        - name: wait for iptables to be reset
          shell: iptables -L | grep 6641
          register: wait_for_iptables
          until: wait_for_iptables.rc != 0
          retries: 200
          delay: 5

      rescue:
        - debug:
            msg: "iptables are reset..."
      always:

#        - name: open ports for ovn
#          iptables:
#            chain: IN_public_allow
#            ctstate: NEW
#            jump: ACCEPT
#            destination_port: '{{ item }}'
#            protocol: tcp
#            match: state
#          loop:
#            - "6641"
#            - "6642"
#            - "6081"
#
#        - name: open ports for dnsmasq
#          iptables:
#            chain: IN_public_allow
#            ctstate: NEW,ESTABLISHED
#            jump: ACCEPT
#            destination_port: '53'
#            protocol: '{{ item }}'
#            match: state
#          loop:
#            - tcp
#            - udp

        - name: open ports for ovn
          firewalld:
            zone: public
            port: '{{ item }}/tcp'
            permanent: yes
            state: enabled
          loop:
            - "6641"
            - "6642"
            - "6081"

        - name: open ports for dnsmasq
          firewalld:
            zone: public
            port: '53/{{ item }}'
            permanent: yes
            state: enabled
          loop:
            - tcp
            - udp