- hosts: masters
  become: yes
  tasks:
  #check existing sa for openshift-infra
  #oc get sa -n openshift-infra
  #try this next -> oc adm policy add-scc-to-user hostmount-anyuid system:serviceaccount:openshift-infra:pv-recycler-controller
  #to allow non-root low id
  #oadm policy add-scc-to-user nonroot -z default
  #oc adm policy add-scc-to-group anyuid system:authenticated
    - name: create a system account
      shell: oc create sa pv-recycler-controller -n openshift-infra
      ignore_errors: yes
      run_once: yes

    - name: add priviliged
      shell: oc adm policy add-scc-to-user privileged -z pv-recycler-controller -n openshift-infra
      run_once: yes

    - name: add role to system account
      shell: oc adm policy add-cluster-role-to-user system:openshift:controller:pv-recycler-controller pv-recycler-controller -n openshift-infra
      run_once: yes

    - name: allow non-root images
      shell: oc adm policy add-scc-to-group anyuid system:authenticated
      run_once: yes

    - name: read origin master configuration data
      slurp:
        src: /etc/origin/master/master-config.yaml
      register: master_config_raw

    - name: set master_config
      set_fact:
        master_config: "{{ master_config_raw['content'] | b64decode | to_yaml }}"
      tag: add_user

    - debug:
        var: master_config.admissionConfig
      tag: add_user

    - name: add user
      command: htpasswd {{ master_config.oauthConfig.identityProviders[0].provider.file }} {{ lookup('env','K8S_AUTH_USERNAME') }} {{ lookup('env','K8S_AUTH_PASSWORD') }}
      when: master_config.oauthConfig.identityProviders[0].provider.kind == 'HTPasswdPasswordIdentityProvider'
      tag: add_user
