- name: deploy cluster on ovirt with gpu
  hosts: localhost
  become: no
  gather_facts: no
  connection: local
  vars:
    env: ovirt-70
  vars_files:
    - node-config/nodes-{{ env }}-gpu.yml
  roles:
    - ansible-role-ovirt