- name: undeploy cluster on ovirt with gpu
  hosts: all
  become: no
  gather_facts: no
  connection: local
  vars:
    ansible_ssh_password: ''
  vars_files:
    - node-config/nodes-ovirt-70-gpu.yml
  roles:
    - role: ansible-role-ovirt
      role_action: deprovision
      delegate_to: localhost
        run_once: yes