- hosts: nodes
  become: yes
  vars:
    domain: example.com
    dns_servers:
      - 8.8.8.8
      - 8.8.4.4
  tasks:
    - name: stop dnsmasq
      service:
        name: dnsmasq
        state: stopped
      ignore_errors: yes

    - name: remove dnsmasq
      yum:
        name: dnsmasq
        state: absent
      ignore_errors: yes

    - name: copy resolv.conf
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf