- name: undeploy cluster on vmware
  hosts: all
  become: no
  gather_facts: no
  connection: local
  vars_files:
    - node-config/nodes-hybrid-vmware-ovirt-gpu.yml
  roles:
    - role: ansible-role-vmware
      role_action: deprovision
      nodes: "{{ vmware.nodes }}"
      delegate_to: localhost