---

# This is the community build (default)
#ovn_image: "docker.io/ovnkube/ovn-daemonset:latest"
ovn_image: "docker.io/sdndocker/ovn-daemonset:latest"
# This is an official redhat build
# ovn_image: "registry.access.redhat.com/openshift3/ose-ovn-kubernetes:v4.0"
# This is an official (internal) redhat build
# ovn_image: "brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/ose-ovn-kubernetes:v4.0"
# This is an official image on aws
# ovn_image: "registry.reg-aws.openshift.com:443/openshift3/ose-ovn-kubernetes:v4.0"

ovn_image_pull_policy: IfNotPresent
# ovn_image_pull_policy: Always

ovn_kube_master_log_level: 4

ovn_gateway_mode: local706086

ovn_gateway_opts: ""
mtu_value: "1400"

net_cidr: 10.128.0.0/14
svc_cidr: 172.30.0.0/16

ovn_kubernetes_git_url: https://github.com/ovn-org/ovn-kubernetes.git