---
- name: disable cloud-init
  file:
    path: /etc/cloud/cloud-init.disabled
    state: touch
  ignore_errors: yes

- name: configure sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: '^Defaults.*requiretty'
    line: 'Defaults    !requiretty'
    state: present
    validate: visudo -cf %s
    backup: no

- name: install packages
  yum:
    name: NetworkManager
    state: latest

- name: enable and start services
  service:
    name: NetworkManager
    enabled: yes
    state: started