---
- name: disable cloud-init
  file:
    path: /etc/cloud/cloud-init.disabled
    state: touch

- name: configure sudoers
  lineinfile:
    dest: /etc/sudoers
    regexp: '^Defaults.*requiretty'
    line: 'Defaults    !requiretty'
    state: present
    validate: visudo -cf %s
    backup: no

- name: install packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - NetworkManager
  ignore_errors: true

- name: enable and start services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
  - NetworkManager