---
- name: install packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - NetworkManager
  ignore_errors: true

- name: enable and start services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
  - NetworkManager