---

- name: Mkdir \cni
  win_file:
    path: C:\cni
    state: directory
    ignore_errors: yes

- name: Create 10-ovn-kubernetes.conf
  win_copy:
    dest: c:\cni\10-ovn-kubernetes.conf
    force: yes
    content: |
      {"cniVersion":"0.3.1","name":"ovn-kubernetes","type":"ovn-k8s-cni-overlay","ipam":{},"dns":{}}

- name: Copy ovn_k8s.conf to cni directory
  win_copy:
    src: "{{ playbook_dir }}/{{ ansible_hostname }}/ovn_k8s.conf"
    dest: C:\cni\ovn_k8s.conf
    force: yes

- name: Copy ovn_k8s.conf to windows nodes
  win_copy:
    src: "{{ playbook_dir }}/{{ ansible_hostname }}/ovn_k8s.conf"
    dest: C:\Program Files\Cloudbase Solutions\Open vSwitch\conf\ovn_k8s.conf
    force: yes

- name: copy ovn-k8s-cni-overlay.exe
  win_copy:
    src: "{{ playbook_dir }}/cni/bin/ovn-k8s-cni-overlay.exe"
    dest: /bin/ovn-k8s-cni-overlay.exe
    force: yes

- name: copy ovn ovnkube.exe
  win_copy:
    src: "{{ playbook_dir }}/cni/bin/ovnkube.exe"
    dest: /bin/ovnkube.exe
    force: yes