---

- name: Add port 10250 to windows firewall rules
  win_shell: |
    $ErrorActionPreference = "Stop"
    $name = "kubelet"
    $rule = Get-NetFirewallRule -Name $name -ErrorAction SilentlyContinue
    if($rule) {
        # Delete existing rule if found
        Remove-NetFirewallRule -InputObject $rule
    }
    New-NetFirewallRule -Name $name -DisplayName 'Kubernetes Node' `
                        -Enabled True -Direction Inbound `
                        -Protocol TCP -Action Allow -LocalPort 10250
- name: Add port 6081 to windows firewall rules
  win_shell: |
    $ErrorActionPreference = "Stop"
    $name = "ovn.6081"
    $rule = Get-NetFirewallRule -Name $name -ErrorAction SilentlyContinue
    if($rule) {
        # Delete existing rule if found
        Remove-NetFirewallRule -InputObject $rule
    }
    New-NetFirewallRule -Name $name -DisplayName $name -Enabled True `
                        -Direction Inbound -Protocol UDP -Action Allow -LocalPort 6081