---

- name: Set up the GUID for openvswitch
  win_shell: "$GUID = (New-Guid).Guid; Write-Output $GUID"
  register: guid

- debug: msg="GUID is {{ guid.stdout }}"

- name: create a schedule task
  win_scheduled_task:
    name: ovnsetguid
    description: Set OVN System Guid
    actions:
      - path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        arguments: -ExecutionPolicy Unrestricted -NonInteractive ovs-vsctl set Open_vSwitch . external_ids:system-id="{{ guid.stdout | trim  }}"
    triggers:
      - type: boot
        enabled: true
    username: SYSTEM

- name: Run the schedule task
  win_shell: Start-ScheduledTask -TaskName ovnsetguid -AsJob

- name: Setup Kubeovn Service
  win_shell: setup_kubeovn_service.ps1
  args:
    chdir: \k\hybrid\3.11\bin

- name: Setup Kubelet Service
  win_shell: setup_kubelet_service.ps1
  args:
    chdir: \k\hybrid\3.11\bin

- name: Clean up Windows SDN system guid task
  win_scheduled_task:
    name: ovnsetguid
    state: absent