---

- name: find ami id for rhel7
  ec2_ami_facts:
    owners: 309956199498
    filters:
      name: "{{ image_names[ec2_ami_name | default('centos7')] }}"
    region: "{{ ec2_region }}"
  register: rhel7_ami_find

- name: set ami id for rhel7
  set_fact:
    rhel7_ami_id: "{{ rhel7_ami_find.images[-1].image_id | default('') }}"
  when: rhel7_ami_find.images is defined

- debug:
    var: rhel7_ami_id
