---

- name: Make sure there cni directory exist locally
  file:
    path: "{{ playbook_dir }}/cni/bin"
    state: directory
  delegate_to: localhost
  become: no

- name: copy ovn-k8s-cni-overlay.exe
  fetch:
    src: /root/ovn-kubernetes/go-controller/_output/go/windows/ovn-k8s-cni-overlay.exe
    dest: "{{ playbook_dir }}/cni/bin/ovn-k8s-cni-overlay.exe"
    force: yes
    flat: yes

- name: copy ovn ovnkube.exe
  fetch:
    src: /root/ovn-kubernetes/go-controller/_output/go/windows/ovnkube.exe
    dest: "{{ playbook_dir }}/cni/bin/ovnkube.exe"
    force: yes
    flat: yes