---

- name: set hostname to inventory name
  win_hostname:
    name: "{{ inventory_hostname }}"
  register: change_hostname
  when: set_hostname is defined and set_hostname|bool

- name: reboot host if needed
  win_reboot:
  when: change_hostname.reboot_required

- name: build hosts file
  win_lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }}"
    state: present
  when: (hostvars[item].ansible_default_ipv4.address is defined) and (hostvars[item].ec2_private_dns_name is not defined)
  with_items: "{{ play_hosts }}"

- name: build hosts file
  win_lineinfile:
    dest: /etc/hosts
    regex: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ec2_private_dns_name }}"
    state: present
  when: (hostvars[item].ansible_default_ipv4.address is defined) and (hostvars[item].ec2_private_dns_name is defined)
  with_items: "{{ play_hosts }}"
